name: weather_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #  NETWORK
  dio: ^5.4.0
  http: ^1.1.2

  # COMPARISON OBJECT
  equatable: ^2.0.3

  #  STATE MANAGEMENT
  flutter_bloc: ^8.1.3

  # LOCATOR
  get_it: ^7.6.6
  dartz: ^0.10.1

  # FIREBASE
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2

  #  CALENDAR AND DATE TIME
  intl: ^0.19.0

  #  HTML
  flutter_html: ^3.0.0-alpha.3
  flutter_widget_from_html: ^0.14.11

  #  STORAGE
  shared_preferences: ^2.0.6

  shimmer: ^3.0.0
  device_info_plus: ^9.1.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  fluentui_system_icons: ^1.1.223

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
